import os
import csv
import sys
from tree import Node, Tree
from param_generator import param_generate
from discretizer import bias_discretize
from dp_solver import DPAlgorithm

DATA_DIR = "./data"

def load_tree_from_csv(filepath):
    """
    Reconstructs the tree structure from the CSV file generated by main.py
    """
    print(f"Loading tree from: {filepath}")
    
    nodes_map = {} # Tag -> Node object
    
    with open(filepath, 'r', newline='') as f:
        reader = csv.DictReader(f)
        rows = list(reader)
        
        # 1. Create all Node objects first
        for row in rows:
            tag = row['NodeTag']
            utility = float(row['Utility_a'])
            
            # Create node
            node = Node(tag=tag, data={'a': utility})
            nodes_map[tag] = node
        
        # 2. Establish relationships (Parent-Child)
        # We need to find the root to initialize the Tree object
        root_node = None
        
        for row in rows:
            tag = row['NodeTag']
            parent_tag = row['ParentTag']
            node = nodes_map[tag]
            
            if tag == 'root':
                root_node = node
            else:
                # Find parent in map and link
                if parent_tag in nodes_map:
                    parent = nodes_map[parent_tag]
                    # Manually linking child to parent (assuming Node has a children list)
                    parent.children.append(node)
                    # If your Node class has a parent attribute, set it here:
                    # node.parent = parent
        
        if not root_node:
            raise ValueError("Root node not found in CSV.")
            
        # Create Tree wrapper (assuming Tree class takes root as argument)
        tree_obj = Tree('root')
        tree_obj.root = root_node
        
        return tree_obj, nodes_map

def list_tree_files():
    """Lists all tree CSV files in the data directory"""
    if not os.path.exists(DATA_DIR):
        print(f"Error: Directory '{DATA_DIR}' not found.")
        return []
    
    files = [f for f in os.listdir(DATA_DIR) if f.startswith("tree_") and f.endswith(".csv")]
    return sorted(files, reverse=True) # Newest first

# ==========================================
# Main Execution
# ==========================================

# 1. Select File
files = list_tree_files()
if not files:
    print("No tree files found. Please run main.py first.")
    sys.exit()

print("--- Available Tree Structures ---")
for i, f in enumerate(files):
    print(f"{i}: {f}")

try:
    choice = int(input(f"Select file index (0-{len(files)-1}): "))
    selected_file = os.path.join(DATA_DIR, files[choice])
except (ValueError, IndexError):
    print("Invalid selection.")
    sys.exit()

# 2. Load Tree
try:
    mlnl, NODE = load_tree_from_csv(selected_file)
except Exception as e:
    print(f"Error loading tree: {e}")
    sys.exit()

# 3. Input Seed
try:
    seed_input = int(input("Enter random seed (e.g., 100): "))
except ValueError:
    print("Invalid seed.")
    sys.exit()

# 4. Run Simulation
print(f"\n--- Running Simulation with Seed {seed_input} ---")

# Generate Parameters
MU, GAMMA_raw, OMEGA_raw = param_generate(mlnl, NODE, rand_seed=seed_input)

# Solve Raw
print("Solving Raw (Continuous)...")
solver_raw = DPAlgorithm(mlnl, NODE, MU, GAMMA_raw, OMEGA_raw)
j_raw = solver_raw.run()

# Discretize
GAMMA_disc, OMEGA_disc = bias_discretize(GAMMA_raw, OMEGA_raw, MU['root'], rho=0.2)

# Solve Discrete
print("Solving Discrete...")
solver_disc = DPAlgorithm(mlnl, NODE, MU, GAMMA_disc, OMEGA_disc)
j_disc = solver_disc.run()

# Result
print("-" * 30)
print(f"Raw J Value:      {j_raw:.6f}")
print(f"Discrete J Value: {j_disc:.6f}")
print(f"Relative Error:   {abs(j_raw - j_disc) / abs(j_raw) * 100:.4f}%")